AllCops:
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Exclude:
    - rubocop_reporting.gemspec
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - rubocop_reporting.gemspec
    - spec/rubocop_reporting_spec.rb
